"""add language to sources

Revision ID: 0bc53d98abc8
Revises: b7c9fec7e959
Create Date: 2026-07-24 13:23:30.928335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc53d98abc8'
down_revision: Union[str, None] = 'b7c9fec7e959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# All sources that existed before this migration are English-language.
EXISTING_FEED_URLS = [
    "http://feeds.bbci.co.uk/news/rss.xml",
    "https://feeds.npr.org/1001/rss.xml",
    "http://feeds.bbci.co.uk/news/world/rss.xml",
    "https://www.aljazeera.com/xml/rss/all.xml",
    "http://feeds.bbci.co.uk/news/technology/rss.xml",
    "https://techcrunch.com/feed/",
    "https://www.theverge.com/rss/index.xml",
    "http://feeds.bbci.co.uk/news/business/rss.xml",
    "http://feeds.bbci.co.uk/sport/rss.xml",
    "https://www.espn.com/espn/rss/news",
    "http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
    "https://variety.com/feed/",
    "http://feeds.bbci.co.uk/news/health/rss.xml",
    "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
    "https://www.nasa.gov/feed/",
    "https://www.thehindu.com/news/national/feeder/default.rss",
    "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
    "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('language', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###

    sources = sa.table("sources", sa.column("feed_url", sa.String), sa.column("language", sa.String))
    conn = op.get_bind()
    for feed_url in EXISTING_FEED_URLS:
        conn.execute(sources.update().where(sources.c.feed_url == feed_url).values(language="en"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'language')
    # ### end Alembic commands ###
