"""case-insensitive unique index on username

Revision ID: 7dd9e078770d
Revises: aa3b7bff99ee
Create Date: 2026-08-14 14:54:05.749377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd9e078770d'
down_revision: Union[str, None] = 'aa3b7bff99ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.create_index('ix_users_username_lower', 'users', [sa.text('lower(username)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username_lower', table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    # ### end Alembic commands ###
