"""add standalone index on articles.published_at

Revision ID: 833be8e92573
Revises: 5642bea95f4d
Create Date: 2026-07-23 11:10:46.017068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '833be8e92573'
down_revision: Union[str, None] = '5642bea95f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_articles_published_at', 'articles', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_published_at', table_name='articles')
    # ### end Alembic commands ###
