"""add index on sources.city

Revision ID: aa3b7bff99ee
Revises: 2f058becc924
Create Date: 2026-07-24 16:15:38.669415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3b7bff99ee'
down_revision: Union[str, None] = '2f058becc924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sources_city'), 'sources', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_city'), table_name='sources')
    # ### end Alembic commands ###
