"""add region to sources

Revision ID: b7c9fec7e959
Revises: 7f6802164699
Create Date: 2026-07-24 12:09:37.577664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c9fec7e959'
down_revision: Union[str, None] = '7f6802164699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


FEED_REGIONS = {
    "http://feeds.bbci.co.uk/news/rss.xml": "GB",
    "https://feeds.npr.org/1001/rss.xml": "US",
    "http://feeds.bbci.co.uk/news/world/rss.xml": "GB",
    "https://www.aljazeera.com/xml/rss/all.xml": "QA",
    "http://feeds.bbci.co.uk/news/technology/rss.xml": "GB",
    "https://techcrunch.com/feed/": "US",
    "https://www.theverge.com/rss/index.xml": "US",
    "http://feeds.bbci.co.uk/news/business/rss.xml": "GB",
    "http://feeds.bbci.co.uk/sport/rss.xml": "GB",
    "https://www.espn.com/espn/rss/news": "US",
    "http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml": "GB",
    "https://variety.com/feed/": "US",
    "http://feeds.bbci.co.uk/news/health/rss.xml": "GB",
    "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml": "GB",
    "https://www.nasa.gov/feed/": "US",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('region', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###

    sources = sa.table("sources", sa.column("feed_url", sa.String), sa.column("region", sa.String))
    conn = op.get_bind()
    for feed_url, region in FEED_REGIONS.items():
        conn.execute(sources.update().where(sources.c.feed_url == feed_url).values(region=region))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'region')
    # ### end Alembic commands ###
